### ISSUE TITLE
0.7 文档 初始化 WebGLEngine 和引擎版本对不上

### ISSUE THREAD

**Issue by singlecoder** [ant-galaxy/oasis-engine.github.io#449]
初始化 WebGLEngine 的文档和引擎版本对不上 0.7，如下：

<img width="1598" alt="lQLPJxakVR_UN8nNCZTNDHywLaY8Vti5oFcDDk8GvICWAA_3196_2452" src="https://user-images.githubusercontent.com/7200304/187633247-dbeed101-dd6e-4495-a010-4468033ac934.png">

**Comment by eyworldwide** [comment]
We will fix it in 0.9 milestone.

**Comment by cptbtptpbcptdtptp** [comment]
https://github.com/ant-galaxy/oasis-engine.github.io/pull/503
