### ISSUE TITLE
Iteration Plan: Milestone 1.0 - Document

### ISSUE THREAD

**Issue by errnull** [ant-galaxy/oasis-engine.github.io#557]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/1296667/219999101-a4278cb8-536e-4fc6-9e9a-830fd1773fbc.png">

- 介绍和界面 @MrKou47 
- 3D 渲染 @zhuxudong
- 2D 渲染 @singlecoder 
- 动画 @luzhuang 
- 物理 @yangfengzzz
- 脚本 @czizzy

**Comment by errnull** [comment]
> 建议按功能维度来划分目录，比如完成一个 sprite 的功能，不要把“组件“和”资产“割裂开。
> 
> 另外建议调研一下其他编辑器的文档。

调研了一下 Unity 文档，
主要目录如下：
- 背景：简介、应用、安装；
- 界面布局：
- 资源管理：
    - 导入、导出；
- 案例：
    - 快速上手；
- 3D 脚本开发使用：
- GUI: 
- 模型与动画：
- 地形系统；
- 物理引擎：
- 导航系统：

得出的结论是编辑器文档目录可以参考：
静线：
    - 背景、版本介绍；
    - 页面布局介绍：
        - 菜单栏、快捷栏；
        - Hierarchy；
        - Project；
        - Inspector；
        - Scene View；
        - 工具栏、常用工具；
    - 资源管理（导入导出）
 动线：
    - 快速上手教程；
    - 常见案例；

 两方面来规划；

**Comment by errnull** [comment]
- 目录：
    - 静态：
        - 界面：
            - 项目面板；
            - 菜单栏；
            - 层级面板；
            - 视图面板；
            - 资源面板；
            - 检查器；
            - 工具栏；
        - 资产：
            -  导入/导出；
        - 脚本：
            -  JS；
        - 
    - 动态：
        - 快速上手：
        - 基本案例：
    - 补充：
        - 脚本；
        - 物理；
    -

**Comment by errnull** [comment]
- #583

**Comment by errnull** [comment]
调研了一下上传的素材格式、和 CDN 平台，
目前初步考虑使用画眉上传素材，
画眉平台支持的格式主要是 
**图片**

1. png/jpg 
2. webp(上传png手动转，压缩文件大小50%以上)

**动画**

1. 视频格式
2. Gif 在 AE 中转 Mars

操作指引的 Gif 图片文件比较大没办法直接上传；

**Comment by errnull** [comment]
目前使用的截图和录屏工具分别是：

1. 
![image](https://user-images.githubusercontent.com/28481578/206136367-f6c7c139-0eb2-4f0f-be7e-2c91b4728a69.png)
（截图可以带阴影）

1. 
![image](https://user-images.githubusercontent.com/28481578/206136421-249a37f6-eb45-4597-bfba-84880f04bb2e.png)
目前看来动图指引最好有一份视频格式和 gif 格式。

**Comment by errnull** [comment]
- 编辑器：
    - 快速上手：
        - 关于 Oasis Editor：
        - 创建一个旋转立方体：
    - 界面布局：
        - 首页、项目管理：
        - 菜单、工具栏：
        - 层级面板：
        - 视图面板：
        - 检查器：
        - 资源面板：
        - 动画面板：
    - 基础组件：
        - 相机组件；
        - 网格渲染器组件；
        - 动画组件；
        - 粒子组件；
        - 光照组件：
            - 平行光；
            - 聚光灯；
            - 点光源；
        - 精灵组件：
            - 精灵渲染器；
            - 精灵遮罩；
        - 
    - 基本操作：
        - 搭建场景：
            - 创建相机：
            - 创建光照：
            - 创建实体：
                - 变换；
        - 物理相关：
            - 配置碰撞器：
                - 静态碰撞器；
                - 动态碰撞器；
            - 角色控制器；
    - 资产管理：
        - 材质和纹理的使用：
            - 导入纹理：
            - 创建材质：
        - 脚本的开发与使用；
        - 动画编辑：
            - 动画片段的使用
            - 动画控制器的使用；
        - glTF 模型的导入与使用；
        - HDR 的导入与使用；
        - Lottie 动画的导入与使用；
        - 字体的导入与使用；
        - 精灵和精灵图集的使用；
        - ~~Mars 动画导入与使用；~~
        -

**Comment by MrKou47** [comment]
我建议截图不要带阴影，带阴影的截图不适用嵌入到文档中

**Comment by eyworldwide** [comment]
> 我建议截图不要带阴影，带阴影的截图不适用嵌入到文档中

可以在 iShot 的设置里把阴影关闭
<img width="386" alt="image" src="https://user-images.githubusercontent.com/1296667/206373156-421e8d21-f843-47c9-a38d-2e8cb814d675.png">

**Comment by errnull** [comment]
> 我建议截图不要带阴影，带阴影的截图不适用嵌入到文档中

好的，如果不要阴影的话干脆圆角也不要，这样子图片就可以用没有透明通道的压缩格式，
再顺口问一嘴为啥带阴影的图片不适合文档呢，我看它截出来的效果也只是一圈半透明而已，压成 webp 文件其实还好

**Comment by eyworldwide** [comment]
> > 我建议截图不要带阴影，带阴影的截图不适用嵌入到文档中
> 
> 好的，如果不要阴影的话干脆圆角也不要，这样子图片就可以用没有透明通道的压缩格式， 再顺口问一嘴为啥带阴影的图片不适合文档呢，我看它截出来的效果也只是一圈半透明而已，压成 webp 文件其实还好

因为看起来不专业

**Comment by errnull** [comment]
Mac 显示器上的 Retina 屏幕上截出来的图分辨率会自动 x2，（1pt = 2px） 
所以大家尽可能在普通的显示器截图，如果在 mac 上截图麻烦使用 img 标签将图片 *50%，
否则就会出现字体变大的现象:
<img width="532" alt="截屏2022-12-15 19 48 24" src="https://user-images.githubusercontent.com/28481578/207852992-aa7c8533-67a0-4f29-a3a6-2cda9301ed0d.png">
