### ISSUE TITLE
点击 api 文件链接 404

### ISSUE THREAD

**Issue by gz65555** [ant-galaxy/oasis-engine.github.io#568]
点击任意都会报错
![image](https://user-images.githubusercontent.com/6926263/204213407-63dfb685-e17b-4c8c-aa87-9fb1c1ad2484.png)

**Comment by eyworldwide** [comment]
因为路由hash问题，先改成不可点。问题重复：https://github.com/ant-galaxy/oasis-engine.github.io/issues/661
