### ISSUE TITLE
右侧导航栏异常

### ISSUE THREAD

**Issue by zhuxudong** [ant-galaxy/oasis-engine.github.io#642]
* 右侧导航栏和页面内容挤在一起了
* 导航栏不能点击跳转，不能分享相关子标题

![image](https://user-images.githubusercontent.com/17639043/216003381-c5dd39ee-73d1-462c-a6f2-51599c329a78.png)

**Comment by eyworldwide** [comment]
修复了第一个问题，第二个由于单页应用的 hash 问题暂时不可解
